# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-29 14:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_auto_20180429_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='scope',
        ),
    ]
